apiVersion:  external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: path-finder-ai-secret
spec:
  secretStoreRef:
    name: aws-store
    kind: ClusterSecretStore
  target:
    name: path-finder-ai-secret
  data:
    - secretKey: DATABASE_URI #the name in k8
      remoteRef:
        key: path-finder-ai #the name in secret manager
        property: DATABASE_URI #what value to pick in secret manager secret
    - secretKey: GEO_API 
      remoteRef:
        key: path-finder-ai
        property: GEO_API 
    - secretKey: OPENAI_API
      remoteRef:
        key: path-finder-ai
        property: OPENAI_API