apiVersion: v1
kind: Service
metadata:
  name: application-service
  namespace: application
  labels:
    app: path-finder-ai
spec:
  type: ClusterIP
  selector:
    app: path-finder-ai
  ports:
    - name: http 
      protocol: 