apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-servicemonitor
  # namespace: monitoring
  labels:
   release: kube-prometheus-stack
spec:
  # namespaceSelector:
  #   matchNames:
  #     - application
  selector:
    matchLabels:
      app: path-finder-ai
  endpoints:
  - port: http
    interval: 15s
    scrapeTimeout: 14s


